# Menu configuration

[[main]]
  name = "首页"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Android"
  pageRef = "android"
  weight = 20

[[main]]
  name = "Web"
  pageRef = "web"
  weight = 30

[[main]]
  name = "搜索"
  pageRef = "search"
  weight = 40
  [main.params]
    action = "search"

[[main]]
  name = "GitHub"
  url = "https://github.com/overkazaf/reverse_engineering"
  weight = 50
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"
