# Blowfish Theme Parameters
# https://blowfish.page/docs/configuration/#theme-parameters

# 颜色方案
colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true

# 站点信息
enableSearch = true
enableCodeCopy = true
enableImageLazyLoading = true
enableImageWebp = true

# 指纹资源
fingerprint = true

# 文章配置
[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateUpdated = true
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = true
  editURL = "https://github.com/overkazaf/reverse_engineering/tree/master/site/content"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showWordCount = true
  showComments = false
  sharingLinks = false

# 列表配置
[list]
  showBreadcrumbs = true
  showSummary = true
  showViews = false
  showLikes = false
  showTableOfContents = true
  showCards = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  constrainItemsWidth = false

# 站点地图配置
[sitemap]
  excludedKinds = ["taxonomy", "term"]

# 分类法配置
[taxonomy]
  showTermCount = true
  showHero = false
  heroStyle = "background"
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  cardView = false

# 术语配置
[term]
  showHero = false
  heroStyle = "background"
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false

# 首页配置
[homepage]
  layout = "background"
  homepageImage = ""
  showRecent = true
  showRecentItems = 12
  showMoreLink = true
  showMoreLinkDest = "/android/"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true

# 页眉配置
[header]
  layout = "basic"
  logo = ""
  logoDark = ""
  showTitle = true

# 页脚配置
[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

# 作者信息
[author]
  name = "overkazaf"
  image = ""
  headline = "逆向工程爱好者"
  bio = "安全研究 | 数据工程 | AI 协作"
  links = [
    { email = "mailto:overkazaf@gmail.com" },
    { github = "https://github.com/overkazaf" },
  ]
